# 코틀린에서 예외를 다루는 법
---

날짜: 2023-11-02
태그: #코틀린 #예외
메모:

예제 - 주어진 문자열을 정수로 변경:
```kotlin
//java
private int parseIntOrThrow(@Notnull String str) {
	try {
		return Integer.parseInt(str);
	} catch (NumberFormatException e) {
		throw new IllegalArgumentException(String.format("주어진 %s는 숫자가 아닙니다.", str));
	}
}


//kotlin
fun parseIntOrThrow(str: String): Int {
	try {
		return str.toInt()
	} catch (e: NumberFormatException) {
		throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다.")
	}
}
```
- 코틀린에서는 타입이 뒤에 위치
- new를 사용하지 않음
- 문자열 포맷팅이 간단함


자바와 코틀린의 Checked/Unchecked Exception:
```kotlin
//java
//checked 예외를 명시적으로 나타내야 함
public void readFile() throws IOException {
	File currentFile = new File(".");
	File file = new File(currentFile.getAbsolutePath() + "/a.txt");
	BufferedReader reader = new BufferedReader(new FileReader(file));
	reader.readLine();
	reader.close();
}

//kotlin
//checked 예외를 명시적으로 나타내지 않아도 됨
fun readFile() {
	val currentFile = File(".")
	val file = File(currentFile.absolutePath + "/a.txt")
	val reader = BufferedReader(FileReader(file))
	reader.readLine()
	reader.close()
}
```
- 코틀린에서는 checked 예외와 unchecked 예외를 구분하지 않고 모두 unchecked 예외로 처리


자바와 코틀린의 try with resources
```kotlin
//java
public void readFile(String path) throws IOException {
	try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
		reader.readLine()
	}
}

//kotlin
//코틀린에서는 try with resources 구문이 없음
fun readFile(path: String) {
	BufferedReader(FileReader(path)).use { reader -> 
		reader.readLine()
	}
}
```
- try with resources
	- JDK7에서 추가된 기능
	- try안에서 열린 외부 리소스를 자동으로 닫아주는 기능을 함
	- 코틀린에서는 use라는 문법으로 대체됨


출처:
연결문서
